version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: lapini&serra
      WORDPRESS_DB_PASSWORD: 12345678
      WORDPRESS_DB_NAME: sistemas

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sistemas
      MYSQL_USER: lapini&serra
      MYSQL_PASSWORD: 12345678
      MYSQL_RANDOM_ROOT_PASSWORD: '1'